name: Generate Snake Animation

on:
  schedule:
    # Executa uma vez por dia
    - cron: "0 0 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha azul com tema dark
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: JhonatanRodriguesDaSilva
          # Cobrinha azul com cores padrão dos commits (verde)
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#4e7eff&color_dots=#0e4429,#006d32,#26a641,#39d353
          
      # Deploy para o GitHub Pages branch
      - name: Push to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
