name: Generate Snake Animation

on:
  schedule:
    # Executa uma vez por dia
    - cron: "0 0 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - uses: actions/checkout@v3

      # Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: JhonatanRodriguesDaSilva
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
          
      # Deploy para o GitHub Pages branch
      - name: Push to GitHub Pages branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
