name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  
  # Permite executar manualmente pelo GitHub Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v2
      
      # Gera a animação da cobrinha com os commits
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: JhonatanRodriguesDaSilva
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
      
      # Faz o push das imagens geradas para o repositório
      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Atualização da animação de contribuições'
          add: 'dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.gif'
