name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # A cada 24h
  workflow_dispatch:  # Gatilho para rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: JhonatanRodriguesDaSilva
          outputs: |
            dist/github-contribution-grid-snake.svg
          theme: |
            snake_color: "#4e7eff"   # Cor da cobrinha (azul)
            background: "#0d1117"     # Cor do fundo (escuro)
            grid:
              - color: "#0e4429"      # Poucos commits (verde muito escuro)
              - color: "#006d32"      # Verde escuro
              - color: "#26a641"      # Verde médio
              - color: "#39d353"      # Muitos commits (verde claro)
            # Cor de fundo das células da grade (para evitar cinza)
            grid_background: "#0d1117"   # Cor escura para o fundo da grade

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
