name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # A cada 24h, ou você pode ajustar conforme necessário.
  workflow_dispatch:  # Gatilho para rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: JhonatanRodriguesDaSilva
          outputs: |
            dist/github-contribution-grid-snake.svg
          theme: |
            snake_color: "#4e7eff"
            background: "#0d1117"
            grid:
              - color: "#0e4429"
              - color: "#006d32"
              - color: "#26a641"
              - color: "#39d353"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
