name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: JhonatanRodriguesDaSilva
          outputs: |
            ./github-contribution-grid-snake.svg
          theme: |
            snake_color: "#4e7eff"
            background: "#0d1117"
            grid:
              - color: "#0e4429"
              - color: "#006d32"
              - color: "#26a641"
              - color: "#39d353"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update snake"
          git push
